# Generated by Django 4.1.5 on 2023-03-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_alter_measurement_date_alter_measurement_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата'),
        ),
    ]
