# Generated by Django 4.1.5 on 2023-03-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_alter_sensor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
